# action.yaml
name: 'Labrador Action'
description: 'Fetch and load values as environment variables'
inputs:
  config:
    description: 'Specify an alternative config file in the repo.'
    required: false
  aws-ssm-parameters:
    description: 'AWS SSM Parameter Store paths to fetch values from.'
    required: false

branding:
  color: yellow
  icon: download-cloud

runs:
  using: 'composite'
  steps:

      # This is required to find the .labrador.yaml config file.
    - name: Checkout repository code
      uses: actions/checkout@v3

      # This is required for the action to find the shell scripts.
    - name: "Add this action's path to executable path"
      shell: bash
      run: |
        echo "${{ github.action_path }}" >> $GITHUB_PATH
        echo "${{ github.action_path }}/scripts" >> $GITHUB_PATH

    - name: Download Labrador
      shell: bash
      # https://github.com/actions/runner/issues/2473
      # https://github.com/actions/runner/issues/2525
      env:
        GHACTION_LABRADOR_DOCKER_REF: ${{ github.action_ref }}
      run: download-labrador.sh

    - name: Run Labrador
      shell: bash
      env:
        GHACTION_LABRADOR_CONFIG_FILE: ${{ inputs.config }}
        GHACTION_LABRADOR_AWS_PS: ${{ inputs.aws-ssm-parameters }}
      run: run-labrador.sh
