# action.yaml
name: 'Labrador Action'
description: 'Fetch and load values as environment variables'
inputs:
  aws-region:
    description: 'Explicit AWS region, if different from configured environment variables.'
    required: false
  aws-sm-secret:
    description: 'One or more AWS Secrets Manager secrets to fetch values from.'
    required: false
  aws-ssm-parameter:
    description: 'One or more AWS SSM Parameter Store paths to fetch values from. Each can be individual or wildcard.'
    required: false
  config:
    description: 'Specify an alternative Labrador config file in the repo.'
    required: false
  install-only:
    description: 'Only install the Labrador binary in the workflow. Do not fetch any values.'
    required: false
    default: 'false'
  set-env:
    description: 'Set the fetched values as workflow environment variables.'
    required: false
    default: 'true'

branding:
  color: yellow
  icon: download-cloud

runs:
  using: 'composite'
  steps:

      # This is required to find the .labrador.yaml config file.
    - name: Checkout repository code
      uses: actions/checkout@v3

      # This is required for the action to find the shell scripts.
    - name: "Add this action's path to executable path"
      shell: bash
      run: |
        echo "${{ github.action_path }}" >> $GITHUB_PATH
        echo "${{ github.action_path }}/scripts" >> $GITHUB_PATH

    - name: Download Labrador
      shell: bash
      # https://github.com/actions/runner/issues/2473
      # https://github.com/actions/runner/issues/2525
      env:
        GHACTION_LABRADOR_DOCKER_REF: ${{ github.action_ref }}
      run: download-labrador.sh

    - name: Run Labrador
      if: ${{ inputs.install-only == 'false' }}
      shell: bash
      env:
        GHACTION_LABRADOR_CONFIG_FILE: ${{ inputs.config }}
        GHACTION_LABRADOR_SET_ENV: ${{ inputs.set-env }}
        GHACTION_LABRADOR_AWS_REGION: ${{ inputs.aws-region }}
        GHACTION_LABRADOR_AWS_SSM_PARAM: ${{ inputs.aws-ssm-parameter }}
        GHACTION_LABRADOR_AWS_SM_SECRET: ${{ inputs.aws-sm-secret }}
      run: run-labrador.sh
